version: "2"
plugins:
  rubocop:
    enabled: true
    checks:
     Rubocop/Metrics/ClassLength:
       enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
exclude_patterns:
  - "**/__tests__/"
  - "**/*.test.js"
  - "**/node_modules/"
  - "**/db/"
  - "**/knexfile.js"
  - "**/middleware/emailTemplates.js"

# Example .codeclimate.yml from https://docs.codeclimate.com/docs/example-codeclimateyml

# plugins:
#   rubocop:
#     enabled: true
#     #checks:
#     #  Rubocop/Metrics/ClassLength:
#     #    enabled: false
#   brakeman:
#     enabled: true
#   eslint:
#     enabled: true
#   csslint:
#     enabled: true
#   duplication:
#     enabled: true
#     config:
#       languages:
#       - ruby:
#       - javascript:
# exclude_paths:
# - spec/**/*
# - "**/vendor/**/*"